// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Deploy: typeof import('./src/components/Deploy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/Header.vue')['default']
    InitSemantic: typeof import('./src/components/InitSemantic.vue')['default']
    InitWorldCup: typeof import('./src/components/InitWorldCup.vue')['default']
    Mint: typeof import('./src/components/Mint.vue')['default']
    PrivacyDeploy: typeof import('./src/components/PrivacyDeploy.vue')['default']
    PrivacyInitSemantic: typeof import('./src/components/PrivacyInitSemantic.vue')['default']
    PrivacyMint: typeof import('./src/components/PrivacyMint.vue')['default']
    PrivacyWhiteList: typeof import('./src/components/PrivacyWhiteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VList: typeof import('./src/components/VList.vue')['default']
    WelCome: typeof import('./src/components/WelCome.vue')['default']
    WhiteList: typeof import('./src/components/WhiteList.vue')['default']
  }
}

export {}
